services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    # environment:
    #   DB_MYSQL_HOST: "nginx-proxy-manager-db"
    #   DB_MYSQL_PORT: 3306
    #   DB_MYSQL_USER: "root"
    #   DB_MYSQL_PASSWORD: '@nDREE02019868251%'
    #   # DB_MYSQL_NAME: "nginx_proxy"
    #   # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    # depends_on:
    #   - nginx-proxy-manager-db

  # nginx-proxy-manager-db:
  #   container_name: nginx-proxy-manager-db
  #   image: 'jc21/mariadb-aria:latest'
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '@nDREE02019868251%'
  #     MYSQL_DATABASE: 'nginx_proxy'
  #     # MYSQL_USER: 'n3cr0murl0c'
  #     # MYSQL_PASSWORD: 'aNDREE170702'
  #     # MYSQL_USER_HOST: nginx-proxy-manager"
  #     # MYSQL_ROOT_HOST: 172.*.*.* 
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
  #   healthcheck:
  #     test: "mysqladmin ping -h localhost"
  #     interval: 1s
  #     timeout: 1s
  #     retries: 60
  
networks:
  proxy:
    ipam:

      driver: default

      config:
        - subnet: 192.168.1.0/16
        - ip_range: 192.168.1.0/24
        - gateway: 192.168.1.1